name: PR assignment
on:
    pull_request:
        types: [opened, edited, synchronize, reopened, ready_for_review]

jobs:
    auto-assign:
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
        steps:
            - name: 'Auto-assign PR'
              uses: pozil/auto-assign-issue@v2
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  reviewers: |
                    djpark0402
                    k3255
                  assignees: |
                    djpark0402
                    k3255
                  numOfReviewer: 2
                  numOfAssignee: 2
