name: PR assignment
on:
    pull_request:
        types: [opened, edited, synchronize, reopened, ready_for_review]
        
permissions:
  contents: read
  issues: write
  pull-requests: write
  
jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR author and reviewers
        uses: actions/github-script@v6
        with:
          script: |
            const assignees = ['djpark0402', 'k3255']; // 자동으로 할당할 사용자
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              assignees: assignees
            });
